
# OpenSfM will use the default parameters from opensfm/config.py
# Set here any parameter that you want to override for this dataset
# For example:
feature_min_frames_panorama: 100
processes: 4                  # Number of threads to use
feature_type: ASIFT
lowes_ratio: 0.9
sift_peak_threshold: 0.1
robust_matching_threshold: 0.04
robust_matching_min_match: 5
symmetric_matching: no
